---
- name: Add MariaDB repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0xF1656F24C74CD1D8'

- name: Add MariaDB repository 
  apt_repository:
    repo: 'deb [arch=amd64,arm64,ppc64el] http://mirror.netcologne.de/mariadb/repo/{{mariadbver}}/ubuntu {{ansible_distribution_release}} main'

- name: Install MariaDB
  apt:  
    name: [mariadb-server,mariadb-client,mariadb-backup,mariadb-common]

- name: config MariaDB
  template:
    src: my.cnf.jinja2
    dest: /etc/mysql/conf.d/mysql.cnf

- name: create databases dir
  file:
    path: /data/mysql
    state: directory
    owner: mysql
    group: mysql

- name: init Source data
  shell: mysql_install_db --user=mysql --datadir=/data/mysql

- name: Restart MariaDB
  service:
    name: mariadb
    enabled: yes
    state: restarted


- name: Change MariaDB root user password 
  mysql_user: 
    name: root 
    host: localhost
    password: "{{mariadb_password}}"

- name: Removes all anyelse user accounts
  mysql_user:
    login_user: root
    login_password: "{{mariadb_password}}"
    name: ''
    host_all: yes
    state: absent

- name: Remove hostname user accounts
  mysql_user: login_user=root login_password={{mariadb_password}} name='root' host={{ ansible_nodename }} state=absent

- name: Removes test Databases
  mysql_db:
    login_user: root
    login_password: "{{mariadb_password}}"
    name: test
    state: absent

- name: Removing privileges on test database
  command: mysql -uroot -p{{mariadb_password}} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"

- name: del MariaDB Automatically generated for Debian scripts.
  file:
    path: /etc/mysql/debian.cnf
    state: absent


- name: Create a MariaDB  symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: '/etc/mysql/conf.d/mysql.cnf',dest: /data/config/mysqld.cnf}  
