- block: 
  - name: Install apache2
    apt:
      name: [apache2]

  - name: Import Certbot PPA
    apt_repository:
      repo: ppa:certbot/certbot

  - name: Install Certbot
    apt: 
      name: [certbot,python-certbot-apache]

  - name: Create default Directory
    file:
      path: /data/{{item}}
      state: directory
    with_items:
      - wwwroot
      - cert 
      - logs
      - config/apache2

  - name: Create a Apache Log symbolic link
    file:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
      state: link
    with_items:
      - {src: /var/log/apache2,dest: /data/logs/apache2}  # Apache 日志软连接
      - {src: /etc/apache2/sites-enabled,dest: /data/config/apache2/sites-enabled}    # Apache 虚拟主机配置软连接
      - {src: /etc/apache2/mods-enabled,dest: /data/config/apache2/mods-enabled}  # Apache 模块配置软连接

  - name: Change Directory Owner
    file:
      path: /data/{{item}}
      state: directory
      owner: www-data
      group: www-data
    with_items:
      - wwwroot
      - cert

  - name: Start Apache
    service:
      name: apache2
      state: restarted
      enabled: yes

  - name: Check Apache Version
    shell: apache2 -v
    register: apache_ver
    notify: Apache-ubuntu Version
  
  when: webserver == 'apache'


- block:
  - name: import an official nginx signing key
    apt_key: 
      url: https://nginx.org/keys/nginx_signing.key
      state: present

  - name: Import Nginx Official Repo
    apt_repository:
      repo: deb http://nginx.org/packages/ubuntu {{ansible_distribution_release}} nginx
      filename: nginx
      update_cache: yes

  - name: Install Nginx
    apt:
      name: [nginx]
    
  - name: Import Certbot PPA
    apt_repository:
      repo: ppa:certbot/certbot

  - name: Install Certbot
    apt: 
      name: [certbot,python-certbot-nginx]
  
  when: webserver == 'nginx'




