---

- name: Import MySQL GPG Key
  copy: src=RPM-GPG-KEY-mysql dest=/etc/pki/rpm-gpg/

- name: Import MySQL Repo
  template: src=mysql-community.repo.jinja2 dest=/etc/yum.repos.d/mysql-community.repo

- name: Install MySQL{{ mysqlver }}
  yum: name=mysql-community-server state=latest


- name: Create Databases Directory
  file:
    path: /data/mysql
    state: directory
    owner: mysql
    group: mysql
  
- name: Copy MySQL{{mysqlver}} Configuration
  template: src=my.cnf.jinja2 dest=/etc/my.cnf
  notify: restart MySQL

- name: Start MySQL{{mysqlver}} Service
  service: name=mysqld state=started enabled=yes
  
- block:
  - name: MySQL{{mysqlver}} password policy
    lineinfile:
      path: /etc/my.cnf
      regexp: '#validate_password = off'
      line: 'validate_password = off'

  - name: Restart MySQL{{mysqlver}} Service
    service: name=mysqld state=restarted enabled=yes
    
  - name: Get temporary MySQL57+ root password
    shell: grep 'A temporary password is generated for root@localhost:' /var/log/messages | awk '{print $NF}'
    register: mysql_root_temp_password
    
  - name: Change MySQL57+ root user password 
    shell: mysqladmin -u root --password="{{ mysql_root_temp_password.stdout }}" password "{{mysql_password}}"
  when: (mysqlver == '5.7') or (mysqlver == '8.0')


- name: Change MySQL{{ mysqlver }} root user password 
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{mysql_password}}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: (mysqlver == '5.5') or (mysqlver == '5.6')



- name: Removes all anyelse user accounts
  mysql_user:
    login_user: root
    login_password: "{{mysql_password}}"
    name: ''
    host_all: yes
    state: absent

- name: Remove hostname user accounts
  mysql_user: login_user=root login_password={{mysql_password}} name='root' host={{ ansible_nodename }} state=absent


- name: Removes test Databases
  mysql_db:
    login_user: root
    login_password: "{{mysql_password}}"
    name: test
    state: absent

- name: Removing privileges on test database
  command: mysql -uroot -p{{mysql_password}} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"

- name: FLUSH PRIVILEGES
  command: mysql -uroot -p{{mysql_password}} -e "FLUSH PRIVILEGES"


- name: enable remote access
  mysql_user: 
    login_user: root 
    login_password: "{{mysql_password}}"
    name: root
    host: '%'
    password: "{{mysql_password}}"
    priv: '*.*:ALL'
  when: remote 

- name: Create credentials Folder
  file:
    path: /credentials
    state: directory

- name: Create Password doc
  file:
    path: /credentials/password.txt
    mode: 644
    state: touch

- name: Write Databases Password
  shell: echo 'Dtabases root Password:'{{mysql_password}}  > /credentials/password.txt

- name: Databases Random Password
  copy: 
    src: init-5.7.sh
    dest: /root/init.sh
    mode: 0750
  when: (mysqlver == '5.7') or (mysqlver == '8.0')


- name: Databases Random Password
  copy: 
    src: init-5.6.sh
    dest: /root/init.sh
    mode: 0750
  when: (mysqlver == '5.5') or (mysqlver == '5.6')

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750