- name: Install redis
  apt: 
    name: redis
  when: ansible_distribution == 'Ubuntu'

- name: Install redis
  yum: 
    name: redis
  when: ansible_distribution == 'CentOS'

  
- name: Start redis
  service:
    name: redis
    enabled: yes
    state: restarted


- name: Create a redis symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src:  /var/log/redis,dest: /data/logs/redis} 
    - {src:  /etc/redis,dest: /data/config/redis} 



- name: Check redis Version
  shell: redis-server -v
  register: redis_ver
  notify: redis Version
